aws_region     = "ap-south-1"
ami_id         = "ami-06bdd2d56adcaadae"
key_name       = "syed-key"
subnet_id      = "subnet-02089c9ce21c36571"
instance_type  = "t3.micro"
name           = "prod-server"
